import { readFileSync } from "node:fs";

// Machine-readable capability descriptor for autonomous agents that discover
// GoodMemory (e.g. scanning GitHub or hitting a deployed bridge) and want to
// decide, without reading prose, whether and how to give themselves memory.
//
// This module is the single source of truth. Two consumers derive from it:
//   1. The static `.well-known/goodmemory.json` (regenerated by
//      `scripts/generate-capability-descriptor.ts`, golden-checked in tests)
//      that repo scanners fetch straight from the tree.
//   2. The running HTTP bridge, which serves it at
//      `GET /.well-known/goodmemory.json` for agents that reach a deployment.
// Keeping both on one builder means they cannot drift.

const PACKAGE_JSON_URL = new URL("../../package.json", import.meta.url);

let packageVersionCache: string | undefined;

function readPackageVersion(): string {
  if (packageVersionCache) {
    return packageVersionCache;
  }

  const packageJson = JSON.parse(readFileSync(PACKAGE_JSON_URL, "utf8")) as {
    version?: unknown;
  };
  if (
    typeof packageJson.version !== "string" ||
    packageJson.version.length === 0
  ) {
    throw new Error("Unable to read GoodMemory package version.");
  }

  packageVersionCache = packageJson.version;
  return packageVersionCache;
}

export interface GoodMemoryCapabilityOnboardingPath {
  readonly audience: string;
  readonly when: string;
  readonly method: "cli" | "mcp" | "http";
  readonly steps?: readonly string[];
  readonly mcpServer?: {
    readonly command: string;
    readonly args: readonly string[];
  };
  readonly endpoint?: string;
  readonly selfHost?: string;
  readonly pythonClient?: string;
  readonly autoDetect?: string;
  readonly docs: string;
}

export interface GoodMemoryCapabilityBenchmark {
  readonly name: string;
  readonly config: string;
  readonly metric: string;
  readonly result: string;
  readonly reference: string;
  readonly claimDeclaration: string;
}

export interface GoodMemoryCapabilityDescriptor {
  readonly schemaVersion: string;
  readonly name: string;
  readonly version: string;
  readonly kind: "memory-layer";
  readonly summary: string;
  readonly description: string;
  readonly notA: readonly string[];
  readonly license: string;
  readonly homepage: string;
  readonly repository: string;
  readonly documentation: {
    readonly inspector: string;
    readonly llmsTxt: string;
    readonly readme: string;
    readonly quickstart: string;
  };
  readonly install: {
    readonly npmGlobal: string;
    readonly npmPackage: string;
    readonly bun: string;
  };
  readonly memoryApi: readonly string[];
  readonly onboarding: readonly GoodMemoryCapabilityOnboardingPath[];
  readonly mcp: {
    readonly command: string;
    readonly standaloneArgs: readonly string[];
    readonly primaryTools: readonly string[];
    readonly readOnlyToolCount: number;
    readonly writeTool: string;
    readonly registryName: string;
    readonly docs: string;
  };
  readonly http: {
    readonly hosted: string;
    readonly liveness: string;
    readonly wellKnown: string;
    readonly auth: string;
    readonly selfHost: string;
    readonly endpoints: Readonly<Record<string, string>>;
    readonly pythonClient: string;
    readonly docs: string;
  };
  readonly benchmarks: readonly GoodMemoryCapabilityBenchmark[];
  readonly capabilities: {
    readonly localFirst: boolean;
    readonly embeddingFreeDefault: boolean;
    readonly durableStore: string;
    readonly audit: boolean;
    readonly deletion: boolean;
    readonly localInspector: string;
    readonly correctByDefaultRecall: string;
  };
  readonly canonicalSources: {
    readonly prose: string;
    readonly benchmarks: string;
    readonly note: string;
  };
}

const REPO = "https://github.com/hjqcan/GoodMemory";
const HOSTED = "https://goodmemory.vibenest.net";

/**
 * Build the GoodMemory capability descriptor. `options.version` overrides the
 * package.json lookup so tests stay deterministic without filesystem access.
 */
export function buildGoodMemoryCapabilityDescriptor(
  options: { version?: string } = {},
): GoodMemoryCapabilityDescriptor {
  const version = options.version ?? readPackageVersion();

  return {
    schemaVersion: "goodmemory.capability/v1",
    name: "goodmemory",
    version,
    kind: "memory-layer",
    summary:
      "Durable user/project memory layer for chat apps, copilots, and coding agents.",
    description:
      "GoodMemory is the product memory layer between an app or installed agent host and the model runtime: write selected facts, recall the right context, inject it into the next turn, audit what happened, and delete it when it is wrong.",
    notA: ["llm", "agent-framework", "vector-database", "rag-system"],
    license: "MIT",
    homepage: `${REPO}#readme`,
    repository: REPO,
    documentation: {
      inspector: `${REPO}/blob/main/docs/GoodMemory-Inspector-and-Admin-API.md`,
      llmsTxt: `${REPO}/blob/main/llms.txt`,
      readme: `${REPO}#readme`,
      quickstart: `${REPO}#quickstart-codex-or-claude-code-memory`,
    },
    install: {
      npmGlobal: `npm install -g goodmemory@${version}`,
      npmPackage: `npm install goodmemory@${version}`,
      bun: `bun add goodmemory@${version}`,
    },
    memoryApi: [
      "remember",
      "recall",
      "buildContext",
      "feedback",
      "forget",
      "exportMemory",
      "deleteAllMemory",
    ],
    onboarding: [
      {
        audience: "installed-coding-agent-host",
        when: "You are, or run inside, Claude Code or Codex.",
        method: "cli",
        steps: [
          `npm install -g goodmemory@${version}`,
          "goodmemory setup",
          "goodmemory status",
        ],
        autoDetect: "goodmemory adopt",
        docs: `${REPO}#quickstart-codex-or-claude-code-memory`,
      },
      {
        audience: "mcp-client",
        when: "You speak the Model Context Protocol (Cursor, Windsurf, Cline, Claude Desktop, Gemini CLI, OpenCode, or a custom MCP client).",
        method: "mcp",
        mcpServer: {
          command: "goodmemory-mcp",
          args: ["--standalone", "--user-id", "YOUR_USER_ID"],
        },
        autoDetect: "goodmemory adopt",
        docs: `${REPO}#standalone-mcp-for-any-client`,
      },
      {
        audience: "framework-agent-or-backend",
        when: "You are a framework agent (LangGraph, custom loop) or a backend that calls memory as an HTTP service.",
        method: "http",
        endpoint: HOSTED,
        selfHost:
          "goodmemory-http-bridge --recommended OR GOODMEMORY_PROFILE=agent-recommended goodmemory-http-bridge",
        pythonClient: "pip install goodmemory-client",
        docs: `${REPO}#pythonfastapi-http-bridge`,
      },
    ],
    mcp: {
      command: "goodmemory-mcp",
      standaloneArgs: ["--standalone", "--user-id", "YOUR_USER_ID"],
      primaryTools: ["goodmemory_get_context", "goodmemory_remember"],
      readOnlyToolCount: 8,
      writeTool: "goodmemory_remember (opt-in via --allow-write)",
      registryName: "io.github.hjqcan/goodmemory",
      docs: `${REPO}#standalone-mcp-for-any-client`,
    },
    http: {
      hosted: HOSTED,
      liveness: `${HOSTED}/healthz`,
      wellKnown: `${HOSTED}/.well-known/goodmemory.json`,
      auth: "bearer-token",
      selfHost:
        "goodmemory-http-bridge --recommended OR GOODMEMORY_PROFILE=agent-recommended goodmemory-http-bridge",
      endpoints: {
        recall: "POST /memory/recall-context",
        remember: "POST /memory/remember",
        feedback: "POST /memory/feedback",
        export: "POST /memory/export",
        forget: "POST /memory/forget",
        revise: "POST /memory/revise",
      },
      pythonClient: "goodmemory-client (PyPI)",
      docs: `${REPO}#pythonfastapi-http-bridge`,
    },
    benchmarks: [
      {
        name: "LongMemEval",
        config: "full 500",
        metric: "strict judge-free / official judge protocol",
        result: "strict 0.720, official-protocol 0.888",
        reference: "Zep 90.2 (published same-protocol)",
        claimDeclaration: "benchmark-claims/longmemeval.json",
      },
      {
        name: "MemoryAgentBench",
        config: "CR + TTL (scoped)",
        metric: "deterministic answer accuracy, judge-free",
        result: "CR 0.959, TTL 0.767",
        reference: "no-memory ablation 0.000",
        claimDeclaration: "benchmark-claims/memoryagentbench.json",
      },
      {
        name: "LoCoMo",
        config: "full 10 conversations",
        metric: "strict token-F1 / industry LLM-judge protocol",
        result: "strict 0.6117, judge-protocol 0.837",
        reference: "Memori 82.0, Zep 79.1, LangMem 78.1, Mem0 62.5",
        claimDeclaration: "benchmark-claims/locomo.json",
      },
      {
        name: "BEAM",
        config: "100K, 400 questions, 1051 rubric items",
        metric: "official BEAM rubric judge / strict internal binary",
        result: "official 0.802, strict binary 0.7225",
        reference: "only public same-protocol reference 0.49",
        claimDeclaration: "benchmark-claims/beam.json",
      },
      {
        name: "ImplicitMemBench",
        config: "Full-300",
        metric: "stored-answer cross-version judge rescore",
        result: "0.691",
        reference: "upstream-chat baseline 0.400; reference line 0.66",
        claimDeclaration: "benchmark-claims/implicitmembench.json",
      },
    ],
    capabilities: {
      localFirst: true,
      embeddingFreeDefault: true,
      durableStore: "sqlite (default), postgres (opt-in)",
      audit: true,
      deletion: true,
      localInspector:
        "goodmemory inspector serve (loopback-only React console and /admin/v1 API)",
      correctByDefaultRecall:
        "Recall never silently degrades: a downgraded strategy carries routing.warnings (semantic_recall_inactive) and routing.warningMessages (semantic recall inactive — set strategy:hybrid + RETRIEVAL_PRESET) instead of quietly returning the lexical floor.",
    },
    canonicalSources: {
      prose: `${REPO}#readme`,
      benchmarks: `${REPO}/tree/main/benchmark-claims`,
      note: "This descriptor is generated from the GoodMemory package; benchmark numbers are pinned to the gate-verified benchmark-claims/*.json declarations.",
    },
  };
}
